"""
Django settings for {{cookiecutter.project_name}} project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "{{ cookiecutter.django_secret_key }}")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # required for allauth
    "django.contrib.sites",

    # rest framework
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",

    # dj-rest-auth
    "dj_rest_auth",
    "dj_rest_auth.registration",

    # allauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",

    'corsheaders',

    # Local apps
    'users', 

    "drf_yasg",
]

MIDDLEWARE = [
    # corsheaders middleware
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'users.middleware.ConditionalCsrfMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # allauth middleware
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# custom settings 


# simpel JWT
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=10),
    "REFRESH_TOKEN_LIFETIME": timedelta(minutes=20),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

# dj-rest-auth + simplejwt configuration
REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_COOKIE": "jwt-auth",
    "JWT_AUTH_REFRESH_COOKIE": "jwt-refresh-token",
    "JWT_AUTH_COOKIE_USE_CSRF": True,
    "JWT_AUTH_HTTPONLY": True, # keep tokens in cookies secret
    
    # csrf protection
    "JWT_AUTH_SAMESITE": "Lax",       
    "JWT_AUTH_SECURE": not DEBUG, 

    "JWT_AUTH_RETURN_EXPIRATION": True,  
    "SESSION_LOGIN": False,

    "LOGOUT_ON_PASSWORD_CHANGE": False,
    

    # Add later when customizing user serializer
    # "USER_DETAILS_SERIALIZER": "users.api.v1.serializers.CustomUserDetailsSerializer",
}


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "users.authentication.BearerJWTAuthentication",
        "users.authentication.CookieJWTAuthenticationWithCSRF",
        # "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/minute",
        "user": "100/minute",
        "apikey": "100/minute",
        "login": "5/minute",
        "register": "3/hour",
        "password_reset": "3/hour",
        "password_change": "5/hour",
        "token_refresh": "30/minute",
        "logout": "10/minute",
        "dj_rest_auth": "60/minute",
    },
}

# Allauth configuration
ACCOUNT_SIGNUP_FIELDS = ["username*", "email", "password1*", "password2*"]
ACCOUNT_EMAIL_TEMPLATE_EXTENSION = "html"
ACCOUNT_USER_MODEL_USERNAME_FIELD = "username"
ACCOUNT_EMAIL_VERIFICATION = "optional"
ACCOUNT_CONFIRM_EMAIL_ON_GET = False
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_UNIQUE_EMAIL = True

ACCOUNT_DEFAULT_HTTP_PROTOCOL = ('http' if DEBUG else 'https') 

ACCOUNT_EMAIL_CONFIRMATION_HMAC = True
LOGIN_REDIRECT_URL = "/"
OLD_PASSWORD_FIELD_ENABLED = True
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3

ACCOUNT_PASSWORD_RESET_EXPIRE_DAYS = 1  
ACCOUNT_USERNAME_MIN_LENGTH = 3
ACCOUNT_PASSWORD_MIN_LENGTH = 8

ACCOUNT_LOGIN_METHODS = ["username", "email"]
SILENCED_SYSTEM_CHECKS = ["account.W001"]

ACCOUNT_ADAPTER = 'users.adapters.CustomAccountAdapter'


# Email
MAILPIT_ENABLED = False
# Use console backend for development (prints emails to console)
# For production, use SMTP backend with proper email server configuration
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend" if MAILPIT_ENABLED else "django.core.mail.backends.console.EmailBackend" 
EMAIL_HOST = "localhost"
EMAIL_PORT = 1025
EMAIL_USE_TLS = False
EMAIL_USE_SSL = False
EMAIL_HOST_USER = ""
EMAIL_HOST_PASSWORD = ""
DEFAULT_FROM_EMAIL = "noreply@localhost"

# Domain configuration
SITE_ID = 1

#### this is default redirect link
# ACCOUNT_CONFIRM_EMAIL_URL = 'confirm-email/{key}/'
# PASSWORD_RESET_CONFIRM_URL = 'reset-password/{uid}/{token}/'  

CORS_ALLOW_CREDENTIALS = True


# Frontend URLs
FRONTEND_DOMAIN = "{{ cookiecutter.frontend_domain }}"
FRONTEND_URL = f"{ACCOUNT_DEFAULT_HTTP_PROTOCOL}://{FRONTEND_DOMAIN}"

VERIFY_EMAIL_URL = "/verify-email/"
PASSWORD_RESET_URL = "/password-reset/"

CORS_ALLOWED_ORIGINS = [
    FRONTEND_URL,
    ("http://127.0.0.1:3000" if DEBUG else ""),
]

CSRF_TRUSTED_ORIGINS = [
    FRONTEND_URL,
    ("http://127.0.0.1:3000" if DEBUG else ""),
]

# CSRF cookie configuration
CSRF_COOKIE_NAME = "csrftoken_cookie"
CSRF_COOKIE_HTTPONLY = False  


# API Docs settings
SWAGGER_SETTINGS = {
    "USE_SESSION_AUTH": False,

    "PERSIST_AUTH": True,

    # Security schemes (OpenAPI 2.0 style)
    "SECURITY_DEFINITIONS": {
        # For app/SDK clients
        "bearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "Use: Bearer <JWT>",
        },
        # For browser flow: header-only parts (cookies ride automatically)
        "csrfHeader": {
            "type": "apiKey",
            "name": "X-CSRFToken",
            "in": "header",
            "description": "Double-submit CSRF header; value mirrors CSRF cookie.",
        },
        "clientHeader": {
            "type": "apiKey",
            "name": "X-Client",
            "in": "header",
            "description": "Set to 'browser' or 'app'.",
        },
    },

    # Optional: which “security” to apply by default (logical OR across items)
    "DEFAULT_API_SECURITY": [
        {"csrfHeader": [], "clientHeader": []},   # browser
        {"bearerAuth": [], "clientHeader": []},   # app
    ],
}
