"""
Django settings for {{cookiecutter.project_name}} project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "{{ cookiecutter.django_secret_key }}")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # required for allauth
    "django.contrib.sites",

    # rest framework
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",

    # dj-rest-auth
    "dj_rest_auth",
    "dj_rest_auth.registration",

    # allauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",

    'corsheaders',

    # Local apps
    'users', 

    # Api docs 
    "drf_spectacular",
    "drf_spectacular_sidecar",
]

MIDDLEWARE = [
    # corsheaders middleware
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'users.middleware.ConditionalCsrfMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # allauth middleware
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# custom settings 


# simpel JWT
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

# dj-rest-auth + simplejwt configuration
REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_COOKIE": "jwt-auth",
    "JWT_AUTH_REFRESH_COOKIE": "jwt-refresh-token",
    "JWT_AUTH_COOKIE_USE_CSRF": True,
    "JWT_AUTH_HTTPONLY": True, # keep tokens in cookies secret
    
    # csrf protection
    "JWT_AUTH_SAMESITE": "Lax",       
    "JWT_AUTH_SECURE": not DEBUG, 

    "JWT_AUTH_RETURN_EXPIRATION": True,  
    "SESSION_LOGIN": False,

    "LOGOUT_ON_PASSWORD_CHANGE": False,
    
    # Tokens handled by CookiesOrAuthorizationJWTMixin based on Origin header
    # "TOKEN_MODEL": None,

    # serializer configuration
    # "USER_DETAILS_SERIALIZER": "users.api.v1.serializers.CustomUserDetailsSerializer",
}


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "users.authentication.BearerJWTAuthentication",
        "users.authentication.CookieJWTAuthenticationWithCSRF",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "apikey": "100/minute",
    },
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# Allauth configuration
ACCOUNT_SIGNUP_FIELDS = ["username*", "email", "password1*", "password2*"]
ACCOUNT_EMAIL_TEMPLATE_EXTENSION = "html"
ACCOUNT_USER_MODEL_USERNAME_FIELD = "username"
ACCOUNT_EMAIL_VERIFICATION = "optional"
ACCOUNT_CONFIRM_EMAIL_ON_GET = False
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_UNIQUE_EMAIL = True

ACCOUNT_DEFAULT_HTTP_PROTOCOL = ('http' if DEBUG else 'https') 

ACCOUNT_EMAIL_CONFIRMATION_HMAC = True
LOGIN_REDIRECT_URL = "/"
OLD_PASSWORD_FIELD_ENABLED = True
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3

ACCOUNT_PASSWORD_RESET_EXPIRE_DAYS = 1  
ACCOUNT_USERNAME_MIN_LENGTH = 3
ACCOUNT_PASSWORD_MIN_LENGTH = 8

ACCOUNT_LOGIN_METHODS = ["username", "email"]
SILENCED_SYSTEM_CHECKS = ["account.W001"]

ACCOUNT_ADAPTER = 'users.adapters.CustomAccountAdapter'


# Email
MAILPIT_ENABLED = False
# Use console backend for development (prints emails to console)
# For production, use SMTP backend with proper email server configuration
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend" if MAILPIT_ENABLED else "django.core.mail.backends.console.EmailBackend" 
EMAIL_HOST = "localhost"
EMAIL_PORT = 1025
EMAIL_USE_TLS = False
EMAIL_USE_SSL = False
EMAIL_HOST_USER = ""
EMAIL_HOST_PASSWORD = ""
DEFAULT_FROM_EMAIL = "noreply@localhost"

# Domain configuration
SITE_ID = 1

#### this is default redirect link
# ACCOUNT_CONFIRM_EMAIL_URL = 'confirm-email/{key}/'
# PASSWORD_RESET_CONFIRM_URL = 'reset-password/{uid}/{token}/'  

CORS_ALLOW_CREDENTIALS = True


# Frontend URLs
FRONTEND_DOMAIN = "{{ cookiecutter.frontend_domain }}"
FRONTEND_URL = f"{ACCOUNT_DEFAULT_HTTP_PROTOCOL}://{FRONTEND_DOMAIN}"

VERIFY_EMAIL_URL = "/verify-email/"
PASSWORD_RESET_URL = "/password-reset/"

CORS_ALLOWED_ORIGINS = [
    FRONTEND_URL,
    ("http://127.0.0.1:3000" if DEBUG else ""),
]

CSRF_TRUSTED_ORIGINS = [
    FRONTEND_URL,
    ("http://127.0.0.1:3000" if DEBUG else ""),
]

# CSRF cookie configuration
CSRF_COOKIE_NAME = "csrftoken_cookie"
CSRF_COOKIE_HTTPONLY = False  


# API DOCS
SPECTACULAR_SETTINGS = {
    "TITLE": "{{ cookiecutter.project_name }} API",
    "DESCRIPTION": (
        "REST endpoints secured with a dual-delivery JWT system. "
        "Browser clients send 'X-Client: browser', receive JWTs in the "
        "{auth_cookie} cookie, and must mirror the 'csrftoken_cookie' value in the "
        "'X-CSRFToken' header. Non-browser clients send 'X-Client: app' and use "
        "standard Bearer tokens."
    ).format(auth_cookie=REST_AUTH.get("JWT_AUTH_COOKIE", "jwt-auth")),
    "VERSION": "1.0.0",
    "SECURITY": [
        {"cookieAuth": [], "csrfHeader": [], "clientHeader": []},
        {"bearerAuth": [], "clientHeader": []},
    ],
    "COMPONENTS": {
        "securitySchemes": {
            # Cookie-based session for browser clients
            "cookieAuth": {
                "type": "apiKey",
                "in": "cookie",
                "name": REST_AUTH.get("JWT_AUTH_COOKIE", "jwt-auth"),
                "description": (
                    "JWT access cookie issued to browser clients when 'X-Client: browser' is provided."
                ),
            },
            "csrfHeader": {
                "type": "apiKey",
                "in": "header",
                "name": "X-CSRFToken",
                "description": (
                    "Double-submit CSRF header. Must mirror the value of the 'csrftoken_cookie' cookie."
                ),
            },
            "clientHeader": {
                "type": "apiKey",
                "in": "header",
                "name": "X-Client",
                "description": "Client type selector. Accepts 'browser' or 'app'.",
            },
            # Bearer tokens for app/SDK clients
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
                "description": (
                    "Bearer access token returned to 'X-Client: app' callers."
                ),
            },
        }
    },
    "SWAGGER_UI_SETTINGS": {"persistAuthorization": True},
    "SERVE_INCLUDE_SCHEMA": False,
}